version: '3.2'
services:
  app:
    container_name: app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerdev
    volumes:
      - './app:/usr/src/app'
      - '/usr/src/app/node_modules'
    links:
      - db
    ports:
      - 3000:3000
      - 3100:3100
      - 35729:35729
    env_file: 
      - ./.env
    environment:
      NODE_ENV: development
    depends_on:
      - adminer
    command: ["./wait-for-it.sh", "db:5432", "-s", "--", "npm", "run", "develop"]
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 4040:8080
    depends_on:
      - db
