version: '3.2'
services:
  app:
    container_name: app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerdev
    volumes:
      - ./app:/usr/src/app:rw
    links:
      - db
    ports:
      - 3000:3000
      - 3100:3100
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 4040:8080
